# Generated by Django 3.2.6 on 2021-08-13 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0002_song_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='genre',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
